<a href="https://colab.research.google.com/github/khbae/econometrics/blob/master/exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from vega_datasets import data
import numpy as np

In [ ]:
data.list_datasets()

['7zip',
 'airports',
 'annual-precip',
 'anscombe',
 'barley',
 'birdstrikes',
 'budget',
 'budgets',
 'burtin',
 'cars',
 'climate',
 'co2-concentration',
 'countries',
 'crimea',
 'disasters',
 'driving',
 'earthquakes',
 'ffox',
 'flare',
 'flare-dependencies',
 'flights-10k',
 'flights-200k',
 'flights-20k',
 'flights-2k',
 'flights-3m',
 'flights-5k',
 'flights-airport',
 'gapminder',
 'gapminder-health-income',
 'gimp',
 'github',
 'graticule',
 'income',
 'iowa-electricity',
 'iris',
 'jobs',
 'la-riots',
 'londonBoroughs',
 'londonCentroids',
 'londonTubeLines',
 'lookup_groups',
 'lookup_people',
 'miserables',
 'monarchs',
 'movies',
 'normal-2d',
 'obesity',
 'ohlc',
 'points',
 'population',
 'population_engineers_hurricanes',
 'seattle-temps',
 'seattle-weather',
 'sf-temps',
 'sp500',
 'stocks',
 'udistrict',
 'unemployment',
 'unemployment-across-industries',
 'uniform-2d',
 'us-10m',
 'us-employment',
 'us-state-capitals',
 'volcano',
 'weather',
 'weball26',
 'wheat',

In [ ]:
data.income

In [ ]:
data.jobs(use_local=True)

job    sex  year  count      perc
0     Accountant / Auditor    men  1850    708  0.000131
1     Accountant / Auditor    men  1860   1805  0.000214
2     Accountant / Auditor    men  1870   1310  0.000100
3     Accountant / Auditor    men  1880   2295  0.000125
4     Accountant / Auditor    men  1900  11753  0.000396
...                    ...    ...   ...    ...       ...
7645                Welder  women  1960  28594  0.000329
7646                Welder  women  1970  48083  0.000440
7647                Welder  women  1980  57920  0.000451
7648                Welder  women  1990  36224  0.000243
7649                Welder  women  2000  63197  0.000376

[7650 rows x 5 columns]

In [ ]:
df = data.cars(use_local=True)

In [ ]:
df.values

array([['chevrolet chevelle malibu', 18.0, 8, ..., 12.0,
        Timestamp('1970-01-01 00:00:00'), 'USA'],
       ['buick skylark 320', 15.0, 8, ..., 11.5,
        Timestamp('1970-01-01 00:00:00'), 'USA'],
       ['plymouth satellite', 18.0, 8, ..., 11.0,
        Timestamp('1970-01-01 00:00:00'), 'USA'],
       ...,
       ['dodge rampage', 32.0, 4, ..., 11.6,
        Timestamp('1982-01-01 00:00:00'), 'USA'],
       ['ford ranger', 28.0, 4, ..., 18.6,
        Timestamp('1982-01-01 00:00:00'), 'USA'],
       ['chevy s-10', 31.0, 4, ..., 19.4,
        Timestamp('1982-01-01 00:00:00'), 'USA']], dtype=object)

In [ ]:
df.columns

Index(['Name', 'Miles_per_Gallon', 'Cylinders', 'Displacement', 'Horsepower',
       'Weight_in_lbs', 'Acceleration', 'Year', 'Origin'],
      dtype='object')

In [ ]:
df['one'] = 1

In [ ]:
df.columns

Index(['Name', 'Miles_per_Gallon', 'Cylinders', 'Displacement', 'Horsepower',
       'Weight_in_lbs', 'Acceleration', 'Year', 'Origin', 'one'],
      dtype='object')

In [ ]:
X = df.loc[:,['one','Cylinders']].values

In [ ]:
Y = df.loc[:,['Acceleration']].values

In [ ]:
Y

array([[12. ],
       [11.5],
       [11. ],
       [12. ],
       [10.5],
       [10. ],
       [ 9. ],
       [ 8.5],
       [10. ],
       [ 8.5],
       [17.5],
       [11.5],
       [11. ],
       [10.5],
       [11. ],
       [10. ],
       [ 8. ],
       [ 8. ],
       [ 9.5],
       [10. ],
       [15. ],
       [15.5],
       [15.5],
       [16. ],
       [14.5],
       [20.5],
       [17.5],
       [14.5],
       [17.5],
       [12.5],
       [15. ],
       [14. ],
       [15. ],
       [13.5],
       [18.5],
       [14.5],
       [15.5],
       [14. ],
       [19. ],
       [20. ],
       [13. ],
       [15.5],
       [15.5],
       [15.5],
       [15.5],
       [12. ],
       [11.5],
       [13.5],
       [13. ],
       [11.5],
       [12. ],
       [12. ],
       [13.5],
       [19. ],
       [15. ],
       [14.5],
       [14. ],
       [14. ],
       [19.5],
       [14.5],
       [19. ],
       [18. ],
       [19. ],
       [20.5],
       [15.5],
       [17. ],
       [23

In [ ]:
X.T.dot(Y)

array([[ 6301. ],
       [33484.7]])

In [ ]:
np.linalg.inv(X.T.dot(X)).dot(X.T.dot(Y))

array([[20.20345604],
       [-0.85542202]])

In [ ]:
import statsmodels.formula.api as sm

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [ ]:
df.columns

Index(['Name', 'Miles_per_Gallon', 'Cylinders', 'Displacement', 'Horsepower',
       'Weight_in_lbs', 'Acceleration', 'Year', 'Origin', 'one'],
      dtype='object')

In [ ]:
results = sm.ols(formula = 'Acceleration ~ Cylinders',data=df).fit()
print(results.summary())

                            OLS Regression Results                            
Dep. Variable:           Acceleration   R-squared:                       0.273
Model:                            OLS   Adj. R-squared:                  0.271
Method:                 Least Squares   F-statistic:                     151.7
Date:                Fri, 06 Nov 2020   Prob (F-statistic):           8.18e-30
Time:                        23:55:35   Log-Likelihood:                -929.39
No. Observations:                 406   AIC:                             1863.
Df Residuals:                     404   BIC:                             1871.
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     20.2035      0.398     50.708      0.0

In [ ]:
beta = np.linalg.inv(X.T.dot(X)).dot(X.T.dot(Y))

In [ ]:
beta

array([[20.20345604],
       [-0.85542202]])

In [ ]:
df.shape[0]

406

In [ ]:
sigma2 = sum((Y - X.dot(beta))**2)/(df.shape[0]-2)

In [ ]:
var_cov = np.linalg.inv(X.T.dot(X))*sigma2

In [ ]:
np.diag(var_cov)

array([0.15874365, 0.00482446])

In [ ]:
beta.shape

(2, 1)

In [ ]:
np.liang.inv(X.T.dot(X))

AttributeError: ignored

In [ ]:
df.loc[:,['Miles_per_Gallon','Cylinders']]

array([[18. ,  8. ],
       [15. ,  8. ],
       [18. ,  8. ],
       [16. ,  8. ],
       [17. ,  8. ],
       [15. ,  8. ],
       [14. ,  8. ],
       [14. ,  8. ],
       [14. ,  8. ],
       [15. ,  8. ],
       [ nan,  4. ],
       [ nan,  8. ],
       [ nan,  8. ],
       [ nan,  8. ],
       [ nan,  8. ],
       [15. ,  8. ],
       [14. ,  8. ],
       [ nan,  8. ],
       [15. ,  8. ],
       [14. ,  8. ],
       [24. ,  4. ],
       [22. ,  6. ],
       [18. ,  6. ],
       [21. ,  6. ],
       [27. ,  4. ],
       [26. ,  4. ],
       [25. ,  4. ],
       [24. ,  4. ],
       [25. ,  4. ],
       [26. ,  4. ],
       [21. ,  6. ],
       [10. ,  8. ],
       [10. ,  8. ],
       [11. ,  8. ],
       [ 9. ,  8. ],
       [27. ,  4. ],
       [28. ,  4. ],
       [25. ,  4. ],
       [25. ,  4. ],
       [ nan,  4. ],
       [19. ,  6. ],
       [16. ,  6. ],
       [17. ,  6. ],
       [19. ,  6. ],
       [18. ,  6. ],
       [14. ,  8. ],
       [14. ,  8. ],
       [14. ,